### ISSUE TITLE
SqlSrv drivers v18 "TrustServerCertificate"

### ISSUE THREAD

**Issue by marshmanGit** [popphp/docs#3]
In class /popphp/pop-db/src/Adapter/Sqlsrv.php, please consider adding a new option for TrustServerCertificate.  The newest drivers automatically force Encryption and many mssql servers use self-signed certs.

    public function setOptions(array $options)
    {
        if (!isset($options['host'])) {
            $options['host'] = 'localhost';
        }

        $this->options = $options;

        $this->info = [
            'Database'                     => $this->options['database'],
            'UID'                              => $this->options['username'],
            'PWD'                            => $this->options['password'],
            'TrustServerCertificate'  => $this->options['TrustServerCertificate']
        ];

**Comment by nicksagona** [comment]
Actually - that's what lines 110-112 are for:

https://github.com/popphp/pop-db/blob/master/src/Adapter/Sqlsrv.php#L110-L112

Those lines allow you to add your own "info" parameters in an array to account for any extra or additional options that might be needed for the SQLServer connection. (Sorry, this wasn't explicitly outlined in the docs.)

It should work with code similar to below, but let me know if you have any issues:

```php
$options = [
    'database' => 'my_database',
    'username' => 'my_db_user',
    'password' => 'my_db_password',
    'host'     => 'mydb.server.com',
    'info'     => [
        'TrustServerCertificate' => true
    ]
];

$sqlsrv = Pop\Db\Db::connect('sqlsrv', $options);
```

**Comment by marshmanGit** [comment]
You are correct sir.  After you patched the   $info to $this-info for the merge array, it works great.  Thanks.
