### ISSUE TITLE
pop-db: Migration example uses "bad" code

### ISSUE THREAD

**Issue by martok** [popphp/docs#5]
The examples for DB migrations show executing the schema via `Adapter::query`, i.e.:
```php
$schema->create('users')
    ->int('id', 16)->increment()
    ->varchar('username', 255)
    ->varchar('password', 255)
    ->primary('id');

$this->db->query($schema);
```

This doesn't actually work as expected as none of the query implementations handle the multi-queries that result from stringifying the `$schema`, so for example adding an index would just not be executed.

Instead letting the schema execute itself with `$schema->execute();` works as expected, but was a bit of a hunt to find in the docs as the example shows the non-working way and the description of execute above does not make it super obvious that this is the "intended"/"only real" way.

**Comment by nicksagona** [comment]
Thanks for the catch. Yes, it should have always been `$schema->execute();` - that was an oversight on my part. It's been corrected and pushed up.

**Comment by martok** [comment]
Great, thank you 👍
